module.exports = {
  OK: 200,
  NOT_FOUND: 404,
  BAD_REQUEST: 400,
  TODAY: 'Today',
  TOMORROW: 'Tomorrow',
  NOT_FOUND_MSG: 'NOT_FOUND_MSG',
  INVALID_ZIP_CODE: 'INVALID_ZIP_CODE',
  SUCCESS_MSG: 'SUCCESS_MSG',
  BAD_REQUEST_MSG: 'BAD_REQUEST_MSG',
  DEFAULT_DEGREE_UNIT: 'F'
}
